### ISSUE TITLE
Review and Edit Measurement Chapter

### ISSUE THREAD

**Issue by jrnold** [jrnold/qss-tidy#18]
Read and edit the introduction chapter. Fix any problems. Expand, revise, or edit the text for clarity. Ask questions in the comments of this issue or open a new issue if there are major changes that need to be made.

Note: when editing the text, keep to code. We can include comments to explain the code, or adds additional information to QSS, but we can't include so much that we are reproducing QSS.

**Comment by calvinhgarner** [comment]
1. Line 31 says:
> With `income`, `r RDoc("readr::read_csv")` never converts strings to factors by default.
But the data is called with data("afghan", package = "qss"), not read_csv.

2. `r RDoc("readr::read_csv")` on Line 31 as written does not appear in the rendered text; I have changed it to `read_csv()`.

3. I moved this to the appropriate location based on the layout of the code chunks in the book.
```{r}
x <- c(1, 2, 3, NA)
mean(x)
mean(x, na.rm = TRUE)
```

4. I don't know how to interpret this line of text:

> The data above is 

5. I added an `alpha` value to these two plots to (better) deal with overplotting. I couldn't get a jitter to work without introducing many more arguments, and opted for simplicity here.

> dens_plot + geom_rug(alpha = .2)

> ```{r}
> ggplot(afghan, aes(y = educ.years, x = province)) +
>   geom_point(position = position_jitter(width = 0.25, height = 0),
>              alpha = .2) +
>   coord_flip() +
>   labs(x = "Province", y = "Years of education",
>        title = "Education by Province")
> ```
> 

6. Is there any easy reference you can add for those who want to find out more about how to do this?

> Also, R Markdown files have their own means of creating and saving plots created by code-chunks.

7. I played around a bit and added the following plot. I like the way it shows 'movement' through time.

> Alternatively, you can plot all values of DW-Nominate scores and use the color to show progress through time. Here, it is essential that you control the `alpha`. Labels can be added to show the mean party position at the first and last congress in the data set. 
> 
> ```{r}
> party_movement <-
>   congress %>% 
>   filter(congress %in% c(80, 112) & party %in% c("Democrat", "Republican")) %>%
>   group_by(party, congress) %>%
>   summarise(mean_dwn1 = mean(dwnom1),
>             mean_dwn2 = mean(dwnom2)) %>%
>   mutate(label = str_c(party, congress, sep = " - "))
> 
> all_congresses <-
>   ggplot(congress, aes(x = dwnom1, y = dwnom2, color = congress)) +
>   geom_point(alpha = 0.15) +
>   geom_label(data = party_movement, aes(x = mean_dwn1, y = mean_dwn2,
>                                        label = label)) +
>   scale_y_continuous("racial liberalism/conservatism",
>                      limits = c(-1.5, 1.5)) +
>   scale_x_continuous("economic liberalism/conservatism",
>                      limits = c(-1.5, 1.5))
> all_congresses
> ```

**Comment by jrnold** [comment]
When you encounter lines like this 

> The data above is

You can fill in something that makes sense, or even delete it. I didn't focus much on the writing of this draft at all. I figured the textbook has the text, and the code chunks here aren't written to be independent of what's in the text.  I only cared much about writing explanations of code that goes beyond what is in the text. So when there's fragmented sentences it's not because I had anything to say. It's because I didn't, and just moved on to writing the next chunk of code.

**Comment by jrnold** [comment]
Is there any easy reference you can add for those who want to find out more about how to do this?

> Also, R Markdown files have their own means of creating and saving plots created by code-chunks.

I was referring to how R Markdown embedds figures in the document. Can you think of a better way of explaining that? 

I think what I meant was that this sentence follows one in which you talk about how a user can use the ggasve function -- did you mean to imply that there were settings through which the user could direct markdown to save the figures separately or control markdowns handling of images? I'm just not clear on this point due to my own lack of familiarity with markdown.

**Comment by jrnold** [comment]
> > With income, r RDoc("readr::read_csv") never converts strings to factors by default.
> But the data is called with data("afghan", package = "qss"), not read_csv.

There's probably other language in this that may refer to previous drafts. I started with csv files, exactly like the book. I found that tedious; replaced it with URLs to the files in github. Found that verbose. Then I wrote the `qss` package and rewrote the code to use that. But I didn't always update text accordingly ...

**Comment by jrnold** [comment]
> I played around a bit and added the following plot. I like the way it shows 'movement' through time.

I like it. But I think there's too much going on when all the points are plotted. It works a lot better when only the means of each party are plotted.  I played around with two versions - one that keeps the colors like you had them, and one that uses the colors for party. What do you think?

**Comment by jrnold** [comment]
![rplot](https://user-images.githubusercontent.com/123968/35135484-6c3610ca-fc92-11e7-8acc-1bd231887089.png)

**Comment by jrnold** [comment]
@calvinhgarner Decide if you like the new plot, and sign off on the R markdown idea. 

Also, I noticed a few plots originally had messages for missing missing values (which was my bad). Chunks should never should messages, warnings, or errors in their output (unless the text is discussing them). If you notice them, can you fix the code to avoid them (preferrable), or suppress them in the knitr chunk options.

**Comment by calvinhgarner** [comment]
New plot looks good! I like the 'cloud' of data, but that might be because I already know what I'm looking at.

**Comment by calvinhgarner** [comment]
Not sure how to suppress the comment about binwidth -- I tried message and warning, but neither of these worked...

> congress %>%
>   filter(congress == 112, party %in% c("Republican", "Democrat")) %>%
>   ggplot(aes(x = dwnom2, y = ..density..)) +
>   geom_histogram() +
>   facet_grid(party ~ .) +
>   labs(x = "racial liberalism/conservatism dimension")

**Comment by calvinhgarner** [comment]
Also, I am trying to run 

> bookdown::serve_book("index.Rmd")

But I am getting the following:

> Error in setwd(dir) : cannot change working directory

I'm not sure why this is happening. Any thoughts?

**Comment by jrnold** [comment]
Confusingly the first arg of `serve_book` is the directory, while `render_book` is a file.
```r
bookdown::serve_book()
```

**Comment by jrnold** [comment]
> New plot looks good! I like the 'cloud' of data, but that might be because I already know what I'm looking at.

The cloud could work if you only included 2-4 congresses instead of all of them.

**Comment by jrnold** [comment]
Specify the `binwidth` argument in `geom_histogram`.

> congress %>%
> filter(congress == 112, party %in% c("Republican", "Democrat")) %>%
> ggplot(aes(x = dwnom2, y = ..density..)) +
> geom_histogram(binwidth = 0.2) +
> facet_grid(party ~ .) +
> labs(x = "racial liberalism/conservatism dimension")

**Comment by calvinhgarner** [comment]
This warning message cropped up after running serve_book(). I don't remember it from before, but I haven't changed all 8 of the Rmd files, so maybe this is normal?

> Warning message:
> In split_chapters(output, gitbook_page, number_sections, split_by,  :
>   You have 8 Rmd input file(s) but only 0 first-level heading(s). Did you forget first-level headings in certain Rmd files?

**Comment by jrnold** [comment]
> This warning message cropped up after running serve_book(). I don't remember it from before, but I haven't changed all 8 of the Rmd files, so maybe this is normal?

Did you figure it out? I pulled the most recent version and built it, and didn't encounter the error message. It happens whenever one of the .Rmd files doesn't start with section, e.g.
```
# Meausurement

blah blah
```
