### ISSUE TITLE
Standardize style for packages & functions

### ISSUE THREAD

**Issue by calvinhgarner** [jrnold/qss-tidy#25]
Currently there is no consistent treatment for packages or functions in the text. Things to consider:

- different first reference in a chapter?

- bolding or putting in r code?

- including () in all functions references?

- adding link to package info on CRAN or elsewhere?

**Comment by jrnold** [comment]
At the moment I'm okay with this inconsistency. It would be a pain to fix all of it, and I don't see it detracting too much. It would be easy to get rid of links programmatically, but that reduces its usefulness.  The style can be no consistent use of linking but functions/objects/packages must either be formatted as below or linked.

- packages are formatted with **bold** (following how Rd files render the `\pkg{}` tag in help and the style of the Journal of Statistical Software)
- functions are formatted with a `monospace` font.  Functions should either be proceeded by the word function, e.g. "the function `filter`", or include `()` after it's name, which indicates that it is a function, e.g. "`filter()`".
