### ISSUE TITLE
Edit Probability Chapter

### ISSUE THREAD

**Issue by jrnold** [jrnold/qss-tidy#7]
Edit the measurment chapter; correct grammatrical/spelling/or substantive mistakes. Expand on anything you thing needs expanding. Comment here if you find something you don't understand.

**Comment by jrnold** [comment]
Were there no issues with these chapters?

**Comment by norawebbwilliams** [comment]
They all passed my initial spellcheck review, but you are right that there may be more substantive issues! I'll reopen this one as a reminder to self.

**Comment by jrnold** [comment]
For all of these, I'd like the more substantive review :-) At least when you are reading them over during the week and with making the keys.
